# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
 - linux
 - osx

julia:
 - 1.0

notifications:
email: false

# This does the documentation
jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl

coveralls: true
coverage: true
